<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Driver;

class DriverSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $drivers = [
            // 2024 Active Drivers (20)
            [
                'first_name' => 'Max',
                'last_name' => 'Verstappen',
                'code' => 'VER',
                'driver_number' => 1,
                'date_of_birth' => '1997-09-30',
                'nationality' => 'Dutch',
                'place_of_birth' => 'Hasselt, Belgium',
                'height_cm' => 181,
                'weight_kg' => 72,
                'debut_year' => '2015-01-01',
                'wins' => 61,
                'podiums' => 105,
                'pole_positions' => 39,
                'fastest_laps' => 35,
                'career_points' => 2831,
                'world_championships' => 3,
                'is_active' => true,
            ],
            [
                'first_name' => 'Sergio',
                'last_name' => 'Perez',
                'code' => 'PER',
                'driver_number' => 11,
                'date_of_birth' => '1990-01-26',
                'nationality' => 'Mexican',
                'place_of_birth' => 'Guadalajara, Mexico',
                'height_cm' => 173,
                'weight_kg' => 63,
                'debut_year' => '2011-01-01',
                'wins' => 6,
                'podiums' => 36,
                'pole_positions' => 3,
                'fastest_laps' => 9,
                'career_points' => 2265,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Lewis',
                'last_name' => 'Hamilton',
                'code' => 'HAM',
                'driver_number' => 44,
                'date_of_birth' => '1985-01-07',
                'nationality' => 'British',
                'place_of_birth' => 'Stevenage, England',
                'height_cm' => 174,
                'weight_kg' => 73,
                'debut_year' => '2007-01-01',
                'wins' => 103,
                'podiums' => 201,
                'pole_positions' => 104,
                'fastest_laps' => 67,
                'career_points' => 4405,
                'world_championships' => 7,
                'is_active' => true,
            ],
            [
                'first_name' => 'George',
                'last_name' => 'Russell',
                'code' => 'RUS',
                'driver_number' => 63,
                'date_of_birth' => '1998-02-15',
                'nationality' => 'British',
                'place_of_birth' => "King's Lynn, UK",
                'height_cm' => 185,
                'weight_kg' => 70,
                'debut_year' => '2019-01-01',
                'wins' => 1,
                'podiums' => 13,
                'pole_positions' => 2,
                'fastest_laps' => 3,
                'career_points' => 599,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Charles',
                'last_name' => 'Leclerc',
                'code' => 'LEC',
                'driver_number' => 16,
                'date_of_birth' => '1997-10-16',
                'nationality' => 'Monegasque',
                'place_of_birth' => 'Monte Carlo, Monaco',
                'height_cm' => 180,
                'weight_kg' => 70,
                'debut_year' => '2018-01-01',
                'wins' => 5,
                'podiums' => 31,
                'pole_positions' => 26,
                'fastest_laps' => 7,
                'career_points' => 1544,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Carlos',
                'last_name' => 'Sainz',
                'code' => 'SAI',
                'driver_number' => 55,
                'date_of_birth' => '1994-09-01',
                'nationality' => 'Spanish',
                'place_of_birth' => 'Madrid, Spain',
                'height_cm' => 178,
                'weight_kg' => 62,
                'debut_year' => '2015-01-01',
                'wins' => 2,
                'podiums' => 20,
                'pole_positions' => 4,
                'fastest_laps' => 4,
                'career_points' => 1105,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Lando',
                'last_name' => 'Norris',
                'code' => 'NOR',
                'driver_number' => 4,
                'date_of_birth' => '1999-11-13',
                'nationality' => 'British',
                'place_of_birth' => 'Bristol, England',
                'height_cm' => 170,
                'weight_kg' => 68,
                'debut_year' => '2019-01-01',
                'wins' => 1,
                'podiums' => 16,
                'pole_positions' => 3,
                'fastest_laps' => 2,
                'career_points' => 631,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Oscar',
                'last_name' => 'Piastri',
                'code' => 'PIA',
                'driver_number' => 81,
                'date_of_birth' => '2001-04-06',
                'nationality' => 'Australian',
                'place_of_birth' => 'Melbourne, Australia',
                'height_cm' => 178,
                'weight_kg' => 68,
                'debut_year' => '2023-01-01',
                'wins' => 2,
                'podiums' => 9,
                'pole_positions' => 2,
                'fastest_laps' => 2,
                'career_points' => 262,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Pierre',
                'last_name' => 'Gasly',
                'code' => 'GAS',
                'driver_number' => 10,
                'date_of_birth' => '1996-02-07',
                'nationality' => 'French',
                'place_of_birth' => 'Rouen, France',
                'height_cm' => 177,
                'weight_kg' => 70,
                'debut_year' => '2017-01-01',
                'wins' => 1,
                'podiums' => 4,
                'pole_positions' => 1,
                'fastest_laps' => 3,
                'career_points' => 537,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Esteban',
                'last_name' => 'Ocon',
                'code' => 'OCO',
                'driver_number' => 31,
                'date_of_birth' => '1996-09-17',
                'nationality' => 'French',
                'place_of_birth' => 'Évreux, France',
                'height_cm' => 186,
                'weight_kg' => 70,
                'debut_year' => '2016-01-01',
                'wins' => 1,
                'podiums' => 3,
                'pole_positions' => 1,
                'fastest_laps' => 2,
                'career_points' => 521,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Fernando',
                'last_name' => 'Alonso',
                'code' => 'ALO',
                'driver_number' => 14,
                'date_of_birth' => '1981-07-29',
                'nationality' => 'Spanish',
                'place_of_birth' => 'Oviedo, Spain',
                'height_cm' => 171,
                'weight_kg' => 68,
                'debut_year' => '2001-01-01',
                'wins' => 32,
                'podiums' => 106,
                'pole_positions' => 22,
                'fastest_laps' => 24,
                'career_points' => 2245,
                'world_championships' => 2,
                'is_active' => true,
            ],
            [
                'first_name' => 'Lance',
                'last_name' => 'Stroll',
                'code' => 'STR',
                'driver_number' => 18,
                'date_of_birth' => '1999-10-29',
                'nationality' => 'Canadian',
                'place_of_birth' => 'Montreal, Canada',
                'height_cm' => 182,
                'weight_kg' => 70,
                'debut_year' => '2017-01-01',
                'wins' => 0,
                'podiums' => 3,
                'pole_positions' => 1,
                'fastest_laps' => 1,
                'career_points' => 332,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Valtteri',
                'last_name' => 'Bottas',
                'code' => 'BOT',
                'driver_number' => 77,
                'date_of_birth' => '1989-04-28',
                'nationality' => 'Finnish',
                'place_of_birth' => 'Helsinki, Finland',
                'height_cm' => 173,
                'weight_kg' => 69,
                'debut_year' => '2013-01-01',
                'wins' => 10,
                'podiums' => 67,
                'pole_positions' => 20,
                'fastest_laps' => 25,
                'career_points' => 1797,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Zhou',
                'last_name' => 'Guanyu',
                'code' => 'ZHO',
                'driver_number' => 24,
                'date_of_birth' => '1999-05-30',
                'nationality' => 'Chinese',
                'place_of_birth' => 'Shanghai, China',
                'height_cm' => 178,
                'weight_kg' => 63,
                'debut_year' => '2022-01-01',
                'wins' => 0,
                'podiums' => 0,
                'pole_positions' => 0,
                'fastest_laps' => 1,
                'career_points' => 62,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Alex',
                'last_name' => 'Albon',
                'code' => 'ALB',
                'driver_number' => 23,
                'date_of_birth' => '1996-03-23',
                'nationality' => 'Thai',
                'place_of_birth' => 'London, UK',
                'height_cm' => 182,
                'weight_kg' => 72,
                'debut_year' => '2019-01-01',
                'wins' => 0,
                'podiums' => 2,
                'pole_positions' => 0,
                'fastest_laps' => 2,
                'career_points' => 321,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Logan',
                'last_name' => 'Sargeant',
                'code' => 'SAR',
                'driver_number' => 2,
                'date_of_birth' => '2000-12-31',
                'nationality' => 'American',
                'place_of_birth' => 'Fort Lauderdale, USA',
                'height_cm' => 178,
                'weight_kg' => 70,
                'debut_year' => '2023-01-01',
                'wins' => 0,
                'podiums' => 0,
                'pole_positions' => 0,
                'fastest_laps' => 0,
                'career_points' => 1,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Ricciardo',
                'code' => 'RIC',
                'driver_number' => 3,
                'date_of_birth' => '1989-07-01',
                'nationality' => 'Australian',
                'place_of_birth' => 'Perth, Australia',
                'height_cm' => 182,
                'weight_kg' => 68,
                'debut_year' => '2011-01-01',
                'wins' => 8,
                'podiums' => 32,
                'pole_positions' => 3,
                'fastest_laps' => 16,
                'career_points' => 1325,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Yuki',
                'last_name' => 'Tsunoda',
                'code' => 'TSU',
                'driver_number' => 22,
                'date_of_birth' => '2000-09-11',
                'nationality' => 'Japanese',
                'place_of_birth' => 'Sagamihara, Japan',
                'height_cm' => 159,
                'weight_kg' => 54,
                'debut_year' => '2021-01-01',
                'wins' => 0,
                'podiums' => 0,
                'pole_positions' => 0,
                'fastest_laps' => 1,
                'career_points' => 44,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Kevin',
                'last_name' => 'Magnussen',
                'code' => 'MAG',
                'driver_number' => 20,
                'date_of_birth' => '1992-10-05',
                'nationality' => 'Danish',
                'place_of_birth' => 'Roskilde, Denmark',
                'height_cm' => 182,
                'weight_kg' => 74,
                'debut_year' => '2014-01-01',
                'wins' => 0,
                'podiums' => 1,
                'pole_positions' => 1,
                'fastest_laps' => 1,
                'career_points' => 389,
                'world_championships' => 0,
                'is_active' => true,
            ],
            [
                'first_name' => 'Nico',
                'last_name' => 'Hulkenberg',
                'code' => 'HUL',
                'driver_number' => 27,
                'date_of_birth' => '1987-08-19',
                'nationality' => 'German',
                'place_of_birth' => 'Bergisch Gladbach, Germany',
                'height_cm' => 184,
                'weight_kg' => 74,
                'debut_year' => '2010-01-01',
                'wins' => 0,
                'podiums' => 0,
                'pole_positions' => 0,
                'fastest_laps' => 2,
                'career_points' => 531,
                'world_championships' => 0,
                'is_active' => true,
            ],
            
            // Reserve Drivers & Recent Retirees
            [
                'first_name' => 'Mick',
                'last_name' => 'Schumacher',
                'code' => 'MSC',
                'driver_number' => 47,
                'date_of_birth' => '1999-03-22',
                'nationality' => 'German',
                'place_of_birth' => 'Geneva, Switzerland',
                'height_cm' => 176,
                'weight_kg' => 67,
                'debut_year' => '2021-01-01',
                'wins' => 0,
                'podiums' => 0,
                'pole_positions' => 0,
                'fastest_laps' => 0,
                'career_points' => 12,
                'world_championships' => 0,
                'is_active' => false,
            ],
            [
                'first_name' => 'Sebastian',
                'last_name' => 'Vettel',
                'code' => 'VET',
                'driver_number' => 5,
                'date_of_birth' => '1987-07-03',
                'nationality' => 'German',
                'place_of_birth' => 'Heppenheim, Germany',
                'height_cm' => 175,
                'weight_kg' => 62,
                'debut_year' => '2007-01-01',
                'wins' => 53,
                'podiums' => 122,
                'pole_positions' => 57,
                'fastest_laps' => 38,
                'career_points' => 3098,
                'world_championships' => 4,
                'is_active' => false,
            ],
            [
                'first_name' => 'Kimi',
                'last_name' => 'Raikkonen',
                'code' => 'RAI',
                'driver_number' => 7,
                'date_of_birth' => '1979-10-17',
                'nationality' => 'Finnish',
                'place_of_birth' => 'Espoo, Finland',
                'height_cm' => 175,
                'weight_kg' => 62,
                'debut_year' => '2001-01-01',
                'wins' => 21,
                'podiums' => 103,
                'pole_positions' => 18,
                'fastest_laps' => 46,
                'career_points' => 1873,
                'world_championships' => 1,
                'is_active' => false,
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Kubica',
                'code' => 'KUB',
                'driver_number' => 8,
                'date_of_birth' => '1984-12-07',
                'nationality' => 'Polish',
                'place_of_birth' => 'Krakow, Poland',
                'height_cm' => 184,
                'weight_kg' => 73,
                'debut_year' => '2006-01-01',
                'wins' => 1,
                'podiums' => 12,
                'pole_positions' => 1,
                'fastest_laps' => 1,
                'career_points' => 537,
                'world_championships' => 0,
                'is_active' => false,
            ],
            [
                'first_name' => 'Felipe',
                'last_name' => 'Massa',
                'code' => 'MAS',
                'driver_number' => 19,
                'date_of_birth' => '1981-04-25',
                'nationality' => 'Brazilian',
                'place_of_birth' => 'Sao Paulo, Brazil',
                'height_cm' => 166,
                'weight_kg' => 60,
                'debut_year' => '2002-01-01',
                'wins' => 11,
                'podiums' => 41,
                'pole_positions' => 16,
                'fastest_laps' => 15,
                'career_points' => 1218,
                'world_championships' => 0,
                'is_active' => false,
            ],
            [
                'first_name' => 'Jenson',
                'last_name' => 'Button',
                'code' => 'BUT',
                'driver_number' => 35,
                'date_of_birth' => '1980-01-19',
                'nationality' => 'British',
                'place_of_birth' => 'Frome, UK',
                'height_cm' => 182,
                'weight_kg' => 70,
                'debut_year' => '2000-01-01',
                'wins' => 15,
                'podiums' => 50,
                'pole_positions' => 8,
                'fastest_laps' => 8,
                'career_points' => 1235,
                'world_championships' => 1,
                'is_active' => false,
            ],
        ];

        foreach ($drivers as $driver) {
            Driver::create($driver);
        }
    }
}
