<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Team;

class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teams = [
            // 2024 Active Teams (10)
            [
                'name' => 'Red Bull Racing',
                'full_name' => 'Oracle Red Bull Racing',
                'code' => 'RBR',
                'country' => 'Austria',
                'headquarters' => 'Milton Keynes, United Kingdom',
                'team_chief' => 'Christian Horner',
                'technical_chief' => 'Pierre Waché',
                'chassis' => 'RB20',
                'power_unit' => 'Honda RBPT',
                'founded_year' => '2005-01-01',
                'world_championships' => 6,
                'race_wins' => 117,
                'pole_positions' => 105,
                'fastest_laps' => 77,
                'podiums' => 254,
                'is_active' => true,
            ],
            [
                'name' => 'Ferrari',
                'full_name' => 'Scuderia Ferrari',
                'code' => 'FER',
                'country' => 'Italy',
                'headquarters' => 'Maranello, Italy',
                'team_chief' => 'Frédéric Vasseur',
                'technical_chief' => 'Enrico Cardile',
                'chassis' => 'SF-24',
                'power_unit' => 'Ferrari',
                'founded_year' => '1950-01-01',
                'world_championships' => 16,
                'race_wins' => 243,
                'pole_positions' => 247,
                'fastest_laps' => 263,
                'podiums' => 834,
                'is_active' => true,
            ],
            [
                'name' => 'Mercedes',
                'full_name' => 'Mercedes-AMG Petronas',
                'code' => 'MER',
                'country' => 'Germany',
                'headquarters' => 'Brackley, United Kingdom',
                'team_chief' => 'Toto Wolff',
                'technical_chief' => 'James Allison',
                'chassis' => 'W15',
                'power_unit' => 'Mercedes',
                'founded_year' => '2010-01-01',
                'world_championships' => 8,
                'race_wins' => 125,
                'pole_positions' => 136,
                'fastest_laps' => 94,
                'podiums' => 294,
                'is_active' => true,
            ],
            [
                'name' => 'McLaren',
                'full_name' => 'McLaren F1 Team',
                'code' => 'MCL',
                'country' => 'United Kingdom',
                'headquarters' => 'Woking, United Kingdom',
                'team_chief' => 'Zak Brown',
                'technical_chief' => 'Peter Prodromou',
                'chassis' => 'MCL38',
                'power_unit' => 'Mercedes',
                'founded_year' => '1966-01-01',
                'world_championships' => 8,
                'race_wins' => 183,
                'pole_positions' => 156,
                'fastest_laps' => 155,
                'podiums' => 511,
                'is_active' => true,
            ],
            [
                'name' => 'Alpine',
                'full_name' => 'BWT Alpine F1 Team',
                'code' => 'ALP',
                'country' => 'France',
                'headquarters' => 'Enstone, United Kingdom',
                'team_chief' => 'Bruno Famin',
                'technical_chief' => 'Matt Harman',
                'chassis' => 'A524',
                'power_unit' => 'Renault',
                'founded_year' => '2021-01-01',
                'world_championships' => 2,
                'race_wins' => 21,
                'pole_positions' => 20,
                'fastest_laps' => 13,
                'podiums' => 79,
                'is_active' => true,
            ],
            [
                'name' => 'Aston Martin',
                'full_name' => 'Aston Martin Aramco Cognizant F1 Team',
                'code' => 'AMR',
                'country' => 'United Kingdom',
                'headquarters' => 'Silverstone, United Kingdom',
                'team_chief' => 'Mike Krack',
                'technical_chief' => 'Dan Fallows',
                'chassis' => 'AMR24',
                'power_unit' => 'Mercedes',
                'founded_year' => '2018-01-01',
                'world_championships' => 0,
                'race_wins' => 0,
                'pole_positions' => 1,
                'fastest_laps' => 1,
                'podiums' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Williams',
                'full_name' => 'Williams Racing',
                'code' => 'WIL',
                'country' => 'United Kingdom',
                'headquarters' => 'Grove, United Kingdom',
                'team_chief' => 'James Vowles',
                'technical_chief' => 'Pat Fry',
                'chassis' => 'FW46',
                'power_unit' => 'Mercedes',
                'founded_year' => '1977-01-01',
                'world_championships' => 9,
                'race_wins' => 114,
                'pole_positions' => 128,
                'fastest_laps' => 133,
                'podiums' => 313,
                'is_active' => true,
            ],
            [
                'name' => 'Haas',
                'full_name' => 'MoneyGram Haas F1 Team',
                'code' => 'HAS',
                'country' => 'United States',
                'headquarters' => 'Kannapolis, United States',
                'team_chief' => 'Guenther Steiner',
                'technical_chief' => 'Rob Taylor',
                'chassis' => 'VF-24',
                'power_unit' => 'Ferrari',
                'founded_year' => '2016-01-01',
                'world_championships' => 0,
                'race_wins' => 0,
                'pole_positions' => 0,
                'fastest_laps' => 0,
                'podiums' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'RB',
                'full_name' => 'RB Visa Cash App Racing Bull F1 Team',
                'code' => 'RB',
                'country' => 'Italy',
                'headquarters' => 'Faenza, Italy',
                'team_chief' => 'Laurent Mekies',
                'technical_chief' => 'Jody Egginton',
                'chassis' => 'VCARB01',
                'power_unit' => 'Honda RBPT',
                'founded_year' => '2006-01-01',
                'world_championships' => 0,
                'race_wins' => 0,
                'pole_positions' => 0,
                'fastest_laps' => 0,
                'podiums' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Sauber',
                'full_name' => 'Stake F1 Team',
                'code' => 'SAU',
                'country' => 'Switzerland',
                'headquarters' => 'Hinwil, Switzerland',
                'team_chief' => 'Alessandro Alunni Bravi',
                'technical_chief' => 'Jan Monchaux',
                'chassis' => 'C44',
                'power_unit' => 'Ferrari',
                'founded_year' => '1993-01-01',
                'world_championships' => 0,
                'race_wins' => 1,
                'pole_positions' => 1,
                'fastest_laps' => 1,
                'podiums' => 27,
                'is_active' => true,
            ],
        ];

        foreach ($teams as $team) {
            Team::create($team);
        }
    }
}
